# Generated by Django 3.2 on 2022-03-12 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_price_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.price'),
        ),
    ]
